CarDealer/Controllers/CarController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using CarDealer.Models;
using CarDealer.Mappers;
using CarDealer.Services;

namespace CarDealer.Controllers
{
    public class CarController : Controller
    {
        private ICarService _service;
        public CarController(ICarService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_service.FindAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CarViewModel car)
        {
            if (ModelState.IsValid)
            {
                this._service.Add(car);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var car = _service.FindById(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpPost]
        public IActionResult Edit(CarViewModel car)
        {
            if (ModelState.IsValid)
            {
                _service.Update(car);
                return RedirectToAction("Index");
            }
            return View(car);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var car = _service.FindById(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var car = _service.FindById(id);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
} 

CarDealer/Controllers/CustomerController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using CarDealer.Models;
using CarDealer.Mappers;
using CarDealer.Services;

namespace CarDealer.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerService _service;
        public CustomerController(ICustomerService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_service.FindAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                this._service.Add(customer);
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var customer = _service.FindById(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [HttpPost]
        public IActionResult Edit(CustomerViewModel customer)
        {
            if (ModelState.IsValid)
            {
                _service.Update(customer);
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var customer = _service.FindById(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var customer = _service.FindById(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

CarDealer/Controllers/SellerController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using CarDealer.Models;
using CarDealer.Mappers;
using CarDealer.Services;

namespace CarDealer.Controllers
{
    public class SellerController : Controller
    {
        private ISellerService _service;
        public SellerController(ISellerService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_service.FindAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(SellerViewModel seller)
        {
            if (ModelState.IsValid)
            {
                this._service.Add(seller);
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var seller = _service.FindById(id);
            if (seller == null)
            {
                return NotFound();
            }
            return View(seller);
        }

        [HttpPost]
        public IActionResult Edit(SellerViewModel seller)
        {
            if (ModelState.IsValid)
            {
                _service.Update(seller);
                return RedirectToAction("Index");
            }
            return View(seller);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var seller = _service.FindById(id);
            if (seller == null)
            {
                return NotFound();
            }
            return View(seller);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var seller = _service.FindById(id);
            if (seller == null)
            {
                return NotFound();
            }
            return View(seller);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
} 

CarDealer/Controllers/TransactionController.cs
using Data;
using Microsoft.AspNetCore.Mvc;
using CarDealer.Models;
using CarDealer.Mappers;
using CarDealer.Services;
using Microsoft.AspNetCore.Authorization;

namespace CarDealer.Controllers
{
    [Authorize(Roles = "admin")]
    public class TransactionController : Controller
    {
        private ITransactionService _service;
        private ICustomerService _customerService;
        private ISellerService _sellerService;
        private ICarService _carService;

        public TransactionController(
            ITransactionService service,
            ICustomerService customerService,
            ISellerService sellerService,
            ICarService carService)
        {
            _service = service;
            _customerService = customerService;
            _sellerService = sellerService;
            _carService = carService;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(_service.FindAll());
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Customers = _customerService.FindAll();
            ViewBag.Sellers = _sellerService.FindAll();
            ViewBag.Cars = _carService.FindAll();
            return View();
        }

        [HttpPost]
        public IActionResult Create(TransactionViewModel transaction)
        {
            if (ModelState.IsValid)
            {
                this._service.Add(transaction);
                return RedirectToAction("Index");
            }
            ViewBag.Customers = _customerService.FindAll();
            ViewBag.Sellers = _sellerService.FindAll();
            ViewBag.Cars = _carService.FindAll();
            return View(transaction);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var transaction = _service.FindById(id);
            if (transaction == null)
            {
                return NotFound();
            }
            ViewBag.Customers = _customerService.FindAll();
            ViewBag.Sellers = _sellerService.FindAll();
            ViewBag.Cars = _carService.FindAll();
            return View(transaction);
        }

        [HttpPost]
        public IActionResult Edit(TransactionViewModel transaction)
        {
            if (ModelState.IsValid)
            {
                _service.Update(transaction);
                return RedirectToAction("Index");
            }
            ViewBag.Customers = _customerService.FindAll();
            ViewBag.Sellers = _sellerService.FindAll();
            ViewBag.Cars = _carService.FindAll();
            return View(transaction);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var transaction = _service.FindById(id);
            if (transaction == null)
            {
                return NotFound();
            }
            return View(transaction);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var transaction = _service.FindById(id);
            if (transaction == null)
            {
                return NotFound();
            }
            return View(transaction);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

CarDealer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarDealer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarDealer.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarDealer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Car" asp-action="Index">Cars</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Seller" asp-action="Index">Sellers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Transactions</a>
                        </li>
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CarDealer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>